### ISSUE TITLE
Duration Type Inconsistency with W3C Specification

### ISSUE THREAD

**Issue by mark-tomlinson-dev** [nclsndr/design-tokens-format-module#4]
Hi @nclsndr, thanks again for this amazing package 😎 

It looks like the current implementation of the Duration type in `src/definitions/tokenTypes.ts` might not be fully compliant with the latest version of the W3C specification for design tokens.

```typescript
export namespace Duration {
// ...
   export type RawValue = `${number}ms` | `${number}s`;
// ...
}
```

According to the W3C spec for duration:
> "Represents the length of time in milliseconds an animation or animation cycle takes to complete, such as 200 milliseconds. The $type property MUST be set to the string duration. The value MUST be a string containing a number (either integer or floating-point) followed by an "ms" unit. A millisecond is a unit of time equal to one thousandth of a second."

If I'm reading that correctly, to align with the W3C spec, the package should update the Duration type to only allow millisecond values:

```typescript
export namespace Duration {
  export type RawValue = `${number}ms;`
// ...
}
```

Apols if I've misunderstood or overlooked something (wouldn't be the first time!)

Let me know if you'd like me to open a PR.

**Comment by nclsndr** [comment]
Thx @mark-tomlinson-dev for reporting the issue.
Now fixed, to be released in few minutes.
